// <auto-generated />
using System;
using EnigmaBot.Recourses.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnigmaBot.Migrations
{
    [DbContext(typeof(SqLitePlayersData))]
    partial class SqLitePlayersDataModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EnigmaBot.Recourses.Database.PlayersActionsCooldown", b =>
                {
                    b.Property<ulong>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FarmCooldown");

                    b.Property<DateTime>("FishingCooldown");

                    b.Property<DateTime>("HuntingCooldown");

                    b.Property<DateTime>("MiningCooldown");

                    b.Property<DateTime>("TravelCooldown");

                    b.Property<DateTime>("WoodChoppingCooldown");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayersCooldowns");
                });

            modelBuilder.Entity("EnigmaBot.Recourses.Database.PlayersMaterialsInventory", b =>
                {
                    b.Property<ulong>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdamantiteBar");

                    b.Property<int>("AdamantiteOre");

                    b.Property<int>("AshWood");

                    b.Property<int>("Beef");

                    b.Property<int>("BirchWood");

                    b.Property<int>("BoarCarcass");

                    b.Property<int>("BoarLeather");

                    b.Property<int>("BoarMeat");

                    b.Property<int>("Bream");

                    b.Property<int>("BuffaloCarcass");

                    b.Property<int>("BuffaloLeather");

                    b.Property<int>("BuffaloMeat");

                    b.Property<int>("BunnyCarcass");

                    b.Property<int>("BunnyLeather");

                    b.Property<int>("BunnyMeat");

                    b.Property<int>("Carp");

                    b.Property<int>("ChickenMeat");

                    b.Property<int>("CopperBar");

                    b.Property<int>("CopperOre");

                    b.Property<int>("Corn");

                    b.Property<int>("Cotton");

                    b.Property<int>("DearMeat");

                    b.Property<int>("DeerCarcass");

                    b.Property<int>("DeerLeather");

                    b.Property<int>("DuckCarcass");

                    b.Property<int>("DuckFeathers");

                    b.Property<int>("DuckMeat");

                    b.Property<int>("EagleCarcass");

                    b.Property<int>("EagleMeat");

                    b.Property<int>("EarleFeathers");

                    b.Property<int>("Eggs");

                    b.Property<int>("ElvenWood");

                    b.Property<int>("FoxCarcass");

                    b.Property<int>("FoxLeather");

                    b.Property<int>("FoxMeat");

                    b.Property<int>("GlowingBar");

                    b.Property<int>("GlowingOre");

                    b.Property<int>("GoldenBar");

                    b.Property<int>("GoldenOre");

                    b.Property<int>("Grapes");

                    b.Property<int>("Grayling");

                    b.Property<int>("IronBar");

                    b.Property<int>("IronOre");

                    b.Property<int>("LeadBar");

                    b.Property<int>("LeadOre");

                    b.Property<int>("MapleWood");

                    b.Property<int>("MeteoriteBar");

                    b.Property<int>("MeteoriteOre");

                    b.Property<int>("Milk");

                    b.Property<int>("OakWood");

                    b.Property<int>("PineWood");

                    b.Property<int>("Potato");

                    b.Property<int>("Raspberry");

                    b.Property<int>("Roach");

                    b.Property<int>("RuddFish");

                    b.Property<int>("RuffFish");

                    b.Property<int>("Salmon");

                    b.Property<int>("SheepMeat");

                    b.Property<int>("SilverBar");

                    b.Property<int>("SilverOre");

                    b.Property<int>("SpruceWood");

                    b.Property<int>("Sterlet");

                    b.Property<int>("Strawberry");

                    b.Property<int>("SweetPepper");

                    b.Property<int>("TheratedAshWood");

                    b.Property<int>("ThreatedBirchWood");

                    b.Property<int>("ThreatedElvenWood");

                    b.Property<int>("ThreatedMapleWood");

                    b.Property<int>("ThreatedOakWood");

                    b.Property<int>("ThreatedPineWood");

                    b.Property<int>("ThreatedSpruceWood");

                    b.Property<int>("ThreatedWalnutWood");

                    b.Property<int>("Tomato");

                    b.Property<int>("Trout");

                    b.Property<int>("WalnutWood");

                    b.Property<int>("WelsCatfish");

                    b.Property<int>("Wheat");

                    b.Property<int>("WolfCarcass");

                    b.Property<int>("WolfLeather");

                    b.Property<int>("WolfMeat");

                    b.Property<int>("Wool");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayersInv");
                });

            modelBuilder.Entity("EnigmaBot.Recourses.Database.PlayersParams", b =>
                {
                    b.Property<ulong>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("BlacksmithSkill");

                    b.Property<string>("CharacterName");

                    b.Property<float>("CookingSkill");

                    b.Property<byte>("CurrentSity");

                    b.Property<float>("FarmingSkill");

                    b.Property<float>("FishingSkill");

                    b.Property<float>("FurnitureMakerSkill");

                    b.Property<float>("HuntingSkill");

                    b.Property<float>("MiningSkill");

                    b.Property<double>("Money");

                    b.Property<float>("OreMeltingSkill");

                    b.Property<float>("SnipperSkill");

                    b.Property<float>("TradeSkill");

                    b.Property<float>("WoodChoppingSkill");

                    b.Property<float>("WoodworkingSkill");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayersParametrs");
                });
#pragma warning restore 612, 618
        }
    }
}
